### ISSUE TITLE
Add support for multiple models

### ISSUE THREAD

**Issue by JackDunnNZ** [OpenSolver/OpenSolverGoogle#4]
We don't have access to an `On Sheet Change` type event, so perhaps we can add support for manually creating different models and the user can pick one from a dropdown, add new ones, and give them names. Open to ideas on this

**Comment by pcebo** [comment]
Second this... unless I'm missing something. Is there a way I can save multiple models related to one sheet? I have a scenario in which I'm iterating and re-running the same 3 models and it sucks to have to build each one again each time.

**Comment by JackDunnNZ** [comment]
Thanks for the feedback! This is the first thing that needs to be fixed, it's really not ideal at the moment.

As I see it, there are two options:

1. Try and figure out some way of detecting a sheet change and then bind models to sheets. We are then limited to one model per sheet a la OpenSolver for Excel
2. Allow construction of multiple models and then user can select one from a dropdown. This lets us have as many models as you want per sheet, but the models are no longer bound to a sheet. I've attached some (very quick) mockups of what this might look like:
![image](https://cloud.githubusercontent.com/assets/4717044/5968340/4db9e3de-a7e4-11e4-8b6f-53bb65cbf496.png)![untitled](https://cloud.githubusercontent.com/assets/4717044/5968313/1acd406a-a7e4-11e4-8216-906c0691b5b5.png)

Any thoughts?

cc @amas008

**Comment by pcebo** [comment]
As much as the 2nd option would be ideal for me in my specific use case right now, I do think that perhaps the 1st option is the preferable method here, if there's a way to detect sheet change as you're suggesting. Still, either is better than none!

(I should also mention that I googled this and ended up here... not realizing until now that we're talking about OpenSolver for Sheets and NOT Excel). Still, happy to give my two cents and if this happens in Sheets OpenSolver first, well then I'll work in Sheets.

**Comment by JackDunnNZ** [comment]
Oh okay. In OpenSolver for Excel, the models are strictly one per sheet to maintain compatibility with the Frontline Solver. If you need to get around this, an option could be to rebuild each of the models in VBA using the Solver API as documented [here](https://msdn.microsoft.com/en-us/library/ff196600.aspx).

FYI the best place to ask Excel-related questions is by posting a comment at opensolver.org. Unfortunately the repository for the Excel version is private.

**Comment by JackDunnNZ** [comment]
Fully implemented as of f104423a9488cc6a99289b57c95d415009812039
