### ISSUE TITLE
OpenSolver Google seems to have stopped posting solutions to Sheets

### ISSUE THREAD

**Issue by jckantor** [OpenSolver/OpenSolverGoogle#9]
In the last couple of days it seems OpenSolver no longer inserts solutions into the variable cells on a sheet.  Has something changed to cause this behavior?

Jeff

**Comment by JackDunnNZ** [comment]
There's a problem with the `LinearOptimizationService` in Google Apps Script and it isn't solving any optimization problems. We have [filed an issue on the bug tracker](https://code.google.com/p/google-apps-script-issues/issues/detail?id=5881) which will be the best place to get updates (please star the issue as well to let them know it's a problem). Sorry I can't help more directly, but this issue needs to be fixed before things will work again.

**Comment by jckantor** [comment]
Thanks!  I added my star to the bug tracker report.

**Comment by jckantor** [comment]
Jack ... any updates on this bug fix.  I see that it's been triaged by Google engineers, but have no idea what that means in terms of getting a fix in place.  Any advice?

**Comment by JackDunnNZ** [comment]
Your guess is as good as mine sorry, they don't seem to be rushing to fix
it. We have a new update that we should be releasing very soon (hopefully
today) with an alternative solver.

**Comment by jckantor** [comment]
Perfect!  Given the overall instability of the various solver options for Sheets, this is excellent news.

**Comment by JackDunnNZ** [comment]
Just a quick update. We've finished and submitted the new version for release, but Google's automatic system has flagged the addon for manual review... hopefully that won't take too long

**Comment by JackDunnNZ** [comment]
Good news! After getting in touch they expedited the review for us, and the update should be rolling out. So there is now an alternative solver that works.

I will update and close this issue once the LinearOptimizationService is fixed.

**Comment by JackDunnNZ** [comment]
The LinearOptimizationService has finally been fixed, so the Google solver is working again.
